# Copyright Jiaqi Liu. All rights reserved.
---
name: executor-docker CI/CD

"on":
  pull_request:
  push:
    branches:
      - master

env:
  USER: QubitPi
  EMAIL: jack20220723@gmail.com

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test

  release:
    name: Publish NPM Packages
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - name: Download auto-version bump scripts
        run: |
            git clone https://github.com/QubitPi/hashicorp-aws.git ../hashicorp-aws
            cp ../hashicorp-aws/.github/tag-for-release.bash .github/
            cp ../hashicorp-aws/.github/upversion.py .github/
      - name: Tag for release
        run: |
            git config --global user.name '$USER'
            git config --global user.email '$EMAIL'
            .github/tag-for-release.bash
      - name: Set release version
        run: |
            VERSION=$(git describe)
            npm version $VERSION
      - name: Publish to NPM Packages
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
